W5/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#new'
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :bands
  resources :albums
end

W5/music_app/app/models/album.rb
class Album < ApplicationRecord
  belongs_to :band
  
  validates :name, :year, :band_id, presence: true
  validates :name, uniqueness: { scope: :band_id }
  validates :band_id, numericality: { minimum: 1900, maximum: 3000 }
  validates :live, inclusion: { in: [true, false] }

  after_initialize :set_defaults

  def set_defaults
    self.live ||= false
  end
end

W5/music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W5/music_app/app/models/band.rb
class Band < ApplicationRecord
  has_many :albums

  validates :name, presence: true


end

W5/music_app/app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, :password_digest, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token
  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    @password = password
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

W5/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      render band_url(album.band)
    else
      flash.now[:errors] = @album.errors.full_messages
    end
  end

  private

  def album_params
    params.require(:album).permit(:name, :year, :live, :band_id)
  end

end

W5/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :logged_in?

  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logout!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end
end

W5/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url
    else
      flash.now[:errors] = @band.errors.full_messages
    end
  end

  def show
    @band = Band.find(params[:id])
    if @band
      render :show
    else
      flash.now[:errors] = @band.errors.full_messages
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

W5/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
              params[:user][:email],
              params[:user][:password])

    if user.nil?
      render json: 'Invalid Credentials'
      render :new
    else
      login!(user)
      redirect_to bands_url
    end
  end

  def destroy
    logout_user!

    redirect_to root_url
  end
end

W5/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_current_user!, except: [:create, :new]

  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to bands_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    if @user
      render :show
    else
      flash.now[:errors] = @user.errors.full_messages
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :session_token, :password_digest, :password)
  end
end

W5/music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

W5/music_app/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input
       name='authenticity_token'
       type='hidden'
       value= #{form_authenticity_token} >".html_safe
  end
end

W5/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

W5/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

W5/music_app/app/helpers/users_helper.rb
module UsersHelper
end

W5/music_app/app/views/albums/new.html.erb
<h1>Add an Album!</h1>
<form class="form" action="<%= albums_url %>" method="post">
  <input type="text" name="album[name]" placeholder="Album Name"><br><br>

  <label for="album_year">Year:</label>
  <select id="album_year" name="album[year]">
    <% (1900..2017).each do |year| %>
    <option value="<%= year %>"> <%= year %> </option>
    <% end %>
  </select>

  <br><br>

  <label for="band_id">Band:</label>
  <select id="band_id" name="album[band_id]">
    <% Band.all.each do |band| %>
    <option value="<%= band.id %>"> <%= band.name %> </option>
    <% end %>
  </select>

  <br><br>
  <label for="">Recording:</label><br>
  <input type="radio" name="album[live]" value="true">Live
  <input type="radio" name="album[live]" value="false">Studio <br>
</form>

W5/music_app/app/views/bands/edit.html.erb
<h1>Edit band!</h1>
<form class="form" action="<%= band_url %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>
  <input type="text" name="band[name]" value= "<%= @band.name %>" ><br>
  <input type="submit" value="Submit">
</form>

W5/music_app/app/views/bands/index.html.erb
<% @bands.each do |band| %>
  <%= link_to "#{band.name}", band_url(band) %><br>
<% end %>

<br>
<%= link_to 'Add a Band', new_band_url %>

W5/music_app/app/views/bands/new.html.erb
<h1>Add a band!</h1>
<form class="form" action=" <%= bands_url %>" method="post">
  <%= auth_token %>
  <input type="text" name="band[name]" placeholder="Band Name"><br>
  <input type="submit" value="Submit">
</form>

W5/music_app/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<div class="buttons">
  <%= link_to 'Edit', edit_band_url, method: "GET" %>
  <%= link_to 'Add an Album', new_album_url %>
  <%= button_to 'Delete', band_url, method: "delete" %>
</div>

W5/music_app/app/views/layouts/_form.html.erb
<% action_url = (method ) %>

<form class="form" action="<%= users_url %>" method="post">

  <input type="text" name="user[email]" placeholder="email"><br>
  <input type="password" name="user[password]" placeholder="password"><br>

</form>

W5/music_app/app/views/layouts/_nav.html.erb
<nav class="nav">
  <% if logged_in? %>
    <h5><%= current_user.email %></h5>
    <h5><%= button_to 'Logout', session_url, method: "delete" %></h5>
  <% else %>
    <h5><%= link_to 'Sign up', new_user_url %></h5>
    <h5><%= link_to 'Sign in', new_session_url %></h5>
  <% end %>
</nav>

W5/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <header>
      <h1>Music App</h1>
      <%= render 'layouts/nav' %>
    </header>
    <div class="content">
      <%= yield %>
    </div>

  </body>
</html>

W5/music_app/app/views/users/new.html.erb
<h1>Sign up!</h1>

<form class="form" action="<%= users_url %>" method="post">
  <%= auth_token %>
  <input type="text" name="user[email]" placeholder="email"><br>
  <input type="password" name="user[password]" placeholder="password"><br>
  <input type="submit" name="" value="submit">
</form>

W5/music_app/app/views/users/show.html.erb
<%= render @user %>